import { clipboard } from "electron";
import { HistoryStore } from "./history-store";

const POLL_INTERVAL_MS = 800;
const SENSITIVE_FORMATS = [
  "org.nspasteboard.ConcealedType",
  "org.nspasteboard.TransientType",
  "org.nspasteboard.AutoGeneratedType",
  "com.agilebits.onepassword",
  "application/x-keepassxc",
];

export class ClipboardMonitor {
  private timer: NodeJS.Timeout | null = null;
  private enabled = false;

  constructor(private readonly history: HistoryStore, private readonly limits: () => { maxItems: number; maxBytes: number }) {}

  setEnabled(enabled: boolean): void {
    this.enabled = enabled;
    if (enabled) this.start();
    else this.stop();
  }

  stop(): void {
    if (this.timer) clearInterval(this.timer);
    this.timer = null;
  }

  private start(): void {
    if (this.timer) return;
    void this.capture();
    this.timer = setInterval(() => void this.capture(), POLL_INTERVAL_MS);
  }

  private capture(): void {
    if (!this.enabled || this.isSensitive()) return;
    const text = clipboard.readText();
    const image = clipboard.readImage();
    if (text.trim()) this.history.addText(text);
    if (!image.isEmpty()) this.history.addImage(image.toPNG());
    const { maxItems, maxBytes } = this.limits();
    this.history.cleanup(maxItems, maxBytes);
  }

  private isSensitive(): boolean {
    return clipboard.availableFormats().some((format) => SENSITIVE_FORMATS.some((sensitive) => format.toLowerCase().includes(sensitive.toLowerCase())));
  }
}
